export const EventType = [
    "All Events",
    "Business Events",
    "Parties",
    "Performances",
    "Sports Events",
    "Festivals",
    "Workshops",
    "Music Events",
    "Exhibitions",
    "Food and Drink Events",
    "Health and Wellness Events",
    "Dance Events",
    "Fashion Events",
    "Arts Events",
    "Fine Arts Events",
    "Theatre Events",
    "Literary Art Events",
    "Craft Events",
    "Photography Events",
    "Cooking Events",
    "Comedy Events",
    "Trips Adventurous Activities",
    "Entertainment Events",
    "Christmas Events",
    "Kids Events",
    "Activities",
    "Conferences",
    "Yoga Events",
    "Hackathons",
    "Virtual Events",
    "Webinar"
]
